# Generated by Django 2.2.3 on 2022-06-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='session name')),
                ('text', models.TextField(verbose_name='session content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videxapp.Course')),
            ],
        ),
    ]
