# Generated by Django 2.2.3 on 2022-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videxuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='balance'),
        ),
        migrations.AddField(
            model_name='videxuser',
            name='telephone_number',
            field=models.CharField(max_length=11, null=True, verbose_name='cellphone number'),
        ),
    ]
