# Generated by Django 2.2.3 on 2022-06-09 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0002_auto_20220609_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='course name')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='videxuser',
            name='finished_courses',
            field=models.ManyToManyField(related_name='finished_courses', to='videxapp.Course'),
        ),
        migrations.AddField(
            model_name='videxuser',
            name='registered_courses',
            field=models.ManyToManyField(related_name='registered_courses', to='videxapp.Course'),
        ),
    ]
