# Generated by Django 2.2.3 on 2022-07-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videxuser',
            name='national_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Number'),
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='exam name')),
                ('release_date', models.DateTimeField()),
                ('deadline_date', models.DateTimeField()),
                ('min_grade', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videxapp.Course')),
            ],
        ),
    ]
