# Generated by Django 4.0.5 on 2022-06-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videxuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
