# Generated by Django 2.2.3 on 2022-07-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0003_alter_videxuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videxuser',
            name='user_img',
            field=models.ImageField(blank=True, default='blank-profile.png', upload_to='images/', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='videxuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='videxuser',
            name='national_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Number'),
        ),
    ]
