# Generated by Django 2.2.3 on 2022-07-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0003_auto_20220704_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videxapp.Chatroom'),
        ),
    ]
