# Generated by Django 2.2.3 on 2022-07-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0004_comment_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videxuser',
            name='finished_courses',
            field=models.ManyToManyField(null=True, related_name='finished_courses', to='videxapp.Course'),
        ),
        migrations.AlterField(
            model_name='videxuser',
            name='registered_courses',
            field=models.ManyToManyField(null=True, related_name='registered_courses', to='videxapp.Course'),
        ),
    ]
