# Generated by Django 2.2.3 on 2022-07-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0004_multiplechoicequestion_singleanswerquestion_writtenquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='answer',
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='answer_id',
            field=models.IntegerField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], default=1),
        ),
    ]
