# Generated by Django 2.2.3 on 2022-07-12 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0005_auto_20220706_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multiplechoicequestion',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='singleanswerquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='singleanswerquestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='singleanswerquestion',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='writtenquestion',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='writtenquestion',
            name='id',
        ),
        migrations.RemoveField(
            model_name='writtenquestion',
            name='question_text',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videxapp.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videxapp.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videxapp.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleanswerquestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videxapp.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writtenquestion',
            name='question_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='videxapp.Question'),
            preserve_default=False,
        ),
    ]
