# Generated by Django 4.0.6 on 2022-07-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0005_alter_course_id_alter_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videxuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume', verbose_name='CV'),
        ),
    ]
