# Generated by Django 2.2.3 on 2022-07-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0006_auto_20220712_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='answer_id',
            new_name='correct_answer_id',
        ),
        migrations.RenameField(
            model_name='singleanswerquestion',
            old_name='answer',
            new_name='correct_answer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videxapp.Question'),
        ),
    ]
