# Generated by Django 4.0.6 on 2022-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0006_videxuser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='videxuser',
            name='card_number',
            field=models.CharField(default='1111111111111111', max_length=16, verbose_name='Credit card number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videxuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='Account balance'),
        ),
    ]
