# Generated by Django 4.0.6 on 2022-07-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0007_videxuser_card_number_alter_videxuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videxuser',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Credit card number'),
        ),
    ]
