# Generated by Django 4.0.6 on 2022-07-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0008_alter_videxuser_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.IntegerField(default=0, help_text='Default is 0$', verbose_name='Course cost'),
        ),
        migrations.AddField(
            model_name='course',
            name='creators',
            field=models.TextField(blank=True, null=True, verbose_name='Creators'),
        ),
        migrations.AddField(
            model_name='course',
            name='ex_len',
            field=models.IntegerField(blank=True, help_text='In weeks', null=True, verbose_name='Expected length'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BA', 'Basic'), ('IN', 'Intermediate'), ('AD', 'Advanced')], default='IN', max_length=2),
        ),
    ]
